# Generated by Django 5.2.12 on 2026-03-19 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('island', models.CharField(choices=[('SANTIAGO', 'Santiago'), ('SAL', 'Sal'), ('BOA_VISTA', 'Boa Vista'), ('SAO_VICENTE', 'São Vicente'), ('SAO_ANTAO', 'Santo Antão'), ('FOGO', 'Fogo'), ('SAO_NICOLAU', 'São Nicolau'), ('MAIO', 'Maio'), ('BRAVA', 'Brava')], default='SANTIAGO', max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(choices=[('CVE', 'CVE'), ('EUR', 'EUR'), ('USD', 'USD')], default='CVE', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='condominium_is_acti_8a3b39_idx')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['condominium', 'floor', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em progresso'), ('RESOLVED', 'Resolvido')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='condominiums.condominium')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='condominiums.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CVE', max_length=3)),
                ('due_date', models.DateField()),
                ('period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Em atraso')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='condominiums.condominium')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='condominiums.unit')),
            ],
            options={
                'ordering': ['-due_date', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['condominium'], name='condominium_condomi_171d2f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['condominium'], name='condominium_condomi_93a8e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('condominium', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['condominium', 'status'], name='condominium_condomi_098ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['condominium', 'priority'], name='condominium_condomi_238139_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['condominium', 'status'], name='condominium_condomi_678f74_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['condominium', 'due_date'], name='condominium_condomi_192fca_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['unit', 'period'], name='condominium_unit_id_c63932_idx'),
        ),
    ]
