# Generated by Django 5.2.12 on 2026-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='actual_cost_cve',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo real final em CVE', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Nome do prestador de serviço', max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to_phone',
            field=models.CharField(blank=True, help_text='Telefone do prestador', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_cost_cve',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo estimado em CVE', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de fotos'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notas sobre a resolução'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Data de resolução', null=True),
        ),
    ]
