# Generated by Django 5.2.12 on 2026-03-19 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0002_maintenancerequest_actual_cost_cve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Piscina, Salão de Festas, Ginásio, Churrasqueira', max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Capacidade máxima de pessoas', null=True)),
                ('rules', models.TextField(blank=True, help_text='Regras de utilização (ex: máx 2h, horário 8h-22h)')),
                ('requires_payment', models.BooleanField(default=False, help_text='Se esta área requer pagamento para reserva')),
                ('price_cve', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa de reserva em CVE', max_digits=10, null=True)),
                ('is_outdoor', models.BooleanField(default=False, help_text='Se a área é ao ar livre (para integração com meteorologia)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['condominium', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resident_name', models.CharField(help_text='Nome do residente que fará a reserva', max_length=255)),
                ('resident_phone', models.CharField(help_text='Telefone/WhatsApp do residente', max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='Data e hora de início')),
                ('end_datetime', models.DateTimeField(help_text='Data e hora de fim')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais da reserva')),
                ('paid_amount_cve', models.DecimalField(blank=True, decimal_places=2, help_text='Valor pago pela reserva (se aplicável)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condominiums.commonarea')),
                ('unit', models.ForeignKey(help_text='Unidade que está a fazer a reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condominiums.unit')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='commonarea',
            index=models.Index(fields=['condominium', 'is_active'], name='condominium_condomi_6c375a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['common_area', 'status'], name='condominium_common__2ddcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['common_area', 'start_datetime'], name='condominium_common__a1c98e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['unit', 'status'], name='condominium_unit_id_ca5583_idx'),
        ),
    ]
