# Generated by Django 5.2.12 on 2026-03-19 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0003_commonarea_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(help_text='Data e hora prevista da assembleia')),
                ('quorum_pct', models.PositiveSmallIntegerField(default=51, help_text='Percentagem mínima de unidades para validar o quórum (0-100)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('OPEN', 'Em Curso'), ('CLOSED', 'Encerrada')], default='SCHEDULED', max_length=20)),
                ('minutes', models.TextField(blank=True, help_text='Acta da assembleia (pós-encerramento)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='condominiums.condominium')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de apresentação')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requires_vote', models.BooleanField(default=True, help_text='Se True, os condóminos podem votar neste ponto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='condominiums.assembly')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('YES', 'Sim'), ('NO', 'Não'), ('ABSTAIN', 'Abstenção')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='condominiums.assemblytopic')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_votes', to='condominiums.unit')),
            ],
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['condominium', 'status'], name='condominium_condomi_cf7580_idx'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['condominium', 'scheduled_at'], name='condominium_condomi_6914c9_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblytopic',
            index=models.Index(fields=['assembly', 'order'], name='condominium_assembl_f1cce1_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['topic'], name='condominium_topic_i_4ea752_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['unit'], name='condominium_unit_id_354e52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblyvote',
            unique_together={('topic', 'unit')},
        ),
    ]
