# Generated by Django 5.2.12 on 2026-03-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0004_assembly_voting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Síndico/gestor responsável pelo condomínio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_condominiums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='condominium',
            index=models.Index(fields=['manager'], name='condominium_manager_70846d_idx'),
        ),
    ]
