services:
  nginx:
    image: nginx:alpine
    container_name: imocv_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    build:
      context: ./src
      target: production
    container_name: imocv_backend
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      target: runner
    container_name: imocv_frontend
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_INTERNAL_API_URL=http://backend:8000
      - TENANT_HOST=206.81.20.231
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.3
    container_name: imocv_db
    env_file:
      - .env.db.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: imocv_redis
    restart: unless-stopped

volumes:
  postgres_data_prod:
