# Generated by Django 5.2.11 on 2026-02-22 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('CHAMADA', 'Chamada Telefónica'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('REUNIAO', 'Reunião Presencial'), ('VISITA', 'Visita ao Imóvel'), ('OUTRO', 'Outro')], default='CHAMADA', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
    ]
