# Generated by Django 5.2.11 on 2026-02-22 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('docs_approved', models.BooleanField(default=False)),
                ('subscription_plan', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], default='STARTER', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/logos/')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('sla_response_time', models.DurationField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
