# Generated by Django 5.2.12 on 2026-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_id_alter_domain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('AGENCY_ADMIN', 'Agency Admin'), ('AGENT', 'Agent'), ('CONDOMINIUM_MANAGER', 'Gestor de Condomínio'), ('BUYER', 'Buyer')], default='BUYER', max_length=20),
        ),
    ]
