# Generated by Django 5.2.11 on 2026-02-22 11:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('MORADIA', 'Moradia/Vila'), ('TERRENO', 'Terreno'), ('COMERCIAL', 'Comercial')], default='APARTAMENTO', max_length=20)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('VENDIDO', 'Vendido'), ('ARRENDADO', 'Arrendado'), ('INATIVO', 'Inativo')], default='RASCUNHO', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='CVE', max_length=3)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('island', models.CharField(choices=[('SANTIAGO', 'Santiago'), ('SAL', 'Sal'), ('BOA_VISTA', 'Boa Vista'), ('SAO_VICENTE', 'São Vicente'), ('SAO_ANTAO', 'Santo Antão'), ('FOGO', 'Fogo'), ('SAO_NICOLAU', 'São Nicolau'), ('MAIO', 'Maio'), ('BRAVA', 'Brava')], default='SANTIAGO', max_length=20)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_garage', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/media/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
