# Generated by Django 5.2.11 on 2026-02-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('ARRENDAMENTO', 'Arrendamento'), ('FERIAS', 'Férias')], default='VENDA', max_length=20),
        ),
    ]
